### ISSUE TITLE
App does not start without internet connection (sometimes)

### ISSUE THREAD

**Issue by borazslo** [Ripityom/Miserend-Android#10]
Megpróbálom leírni, hogy mi történ(hetet)t. 

- Elindításkor (van internet kapcsolat) az app észrevette az adatbázis frissítés szükségességét, de nemet mondtam rá. Később kiléptem.
- Kikapcsoltam minden internetet (mobilnet, wifi). 
- Elindítottam az app-ot, de az összeomlott, el sem indult.
(Többször, sokszor.)

- Később internettel rendelkezve elindítottam. ÉS engedtem, hogy frissítse az adatbázist.
- Kikapcsoltam minden internetet (mobilnet, wifi). 
- Elindítottam az app-ot és minden simán megy.

Azt hiszem Version 2.2.2

**Comment by bmaczak** [comment]
A hiba valószínűleg abból adódik, hogy az app megpróbál bekérdezni a szerverre, hogy van-e friss verzió (azért nem minden indításkor jön elő a hiba, mert csak hetente kérdez be)

**Comment by bmaczak** [comment]
Fixed in fa4dbe8ecbbd46e2b8014689048aa4b88fb6b2d3
